
name: "RunDemoUbuntu"

on:
  push:
    branches: [ "main" ]

jobs:
  analyze:
    name: RunDemoUbuntu
    runs-on: ${{ 'ubuntu-20.04' }}
    timeout-minutes: ${{ 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: ./+run-demo.py
