
name: "RunDemoUbuntu"

on:
  push:
    branches: [ "main" ]
 # pull_request:
    # The branches below must be a subset of the branches above
  #  branches: [ "master" ]
  # schedule:
  #  - cron: '34 4 * * 0'

jobs:
  analyze:
    name: Run
    runs-on: ${{ 'ubuntu-20.04' }}
    timeout-minutes: ${{ 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: |
        ./.github/workflows/run-demo.sh

